name: Publish package to Maven Central
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true
  workflow_call:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: v${{ inputs.version }}
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Check binary compatibility
        run: ./gradlew apiCheck

      - name: Publish artifact
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          
          ORG_GRADLE_PROJECT_signingPassphrase: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signingSecretKey: ${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingPublicKey: ${{ secrets.MAVEN_CENTRAL_GPG_PUBLIC_KEY }}
        run: |
          mkdir -p target/staging-deploy
          ./gradlew publish jreleaserDeploy
